http:
  port: ${APP_PORT}
admin:
  port: ${ADMIN_PORT}
  host: ${ADMIN_HOST}
apiEndpoints:
  matrimony:
    host: ${ENDPOINT}
    paths:
      - "/v1/orders"

  matrimonypublic:
    host: ${ENDPOINT}
    paths:
      - "/v1/booking/ping"

serviceEndpoints:
matrimonysrv:
  url: http://${MATRI_HOST}:${MATRI_SERVICE_PORT}
matrimonysrvpublic:
  url: http://${MATRI_HOST}:${MATRI_SERVICE_PORT}
policies:
  - basic-auth
  - key-auth
  - cors
  - expression
  - log
  - oauth2
  - proxy
  - rate-limit
  - jwt
  - request-transformer
pipelines:
  - name: matrimony-service
    apiEndpoints:
      - matrimony
    policies:
      - cors:
          - action:
            optionsSuccessStatus: 204
      - jwt:
          - action:
              secretOrPublicKey: ${JWT_SECRET}
              checkCredentialExistence: false
      - request-transformer:
          # add user id in request header to use in service
          - action:
              headers:
                add:
                  userid: req.user.id
                  roleid: req.user.roleId
      - proxy:
          - action:
              serviceEndpoint: matrimonysrv
              changeOrigin: true
  - name: matrimony-service-public
    apiEndpoints:
      - matrimonypublic
    policies:
      - proxy:
          - action:
              serviceEndpoint: matrimonysrvpublic
              changeOrigin: true
