http:
  port: ${APP_PORT}
admin:
  port: ${ADMIN_PORT}
  host: ${ADMIN_HOST}
apiEndpoints:
  matrimony:
    host: ${ENDPOINT}
    paths:
      - "/v1/profile/password/change"
      - "/v1/profiles*"

  matrimonypublic:
    host: ${ENDPOINT}
    paths:
      - "/v1/health-check"
      - "/v1/customer/register"
      - "/v1/customer/login"
      - "/v1/customer/mobile-verify"
      - "/v1/customer/password/reset"
      - "/v1/customer/password/update*"

serviceEndpoints:
  matrimonysrv:
    url: http://${MATRI_HOST}:${MATRI_SERVICE_PORT}
  matrimonysrvpublic:
    url: http://${MATRI_HOST}:${MATRI_SERVICE_PORT}
policies:
  - basic-auth
  - key-auth
  - cors
  - expression
  - log
  - oauth2
  - proxy
  - rate-limit
  - jwt
  - request-transformer
pipelines:
  - name: matrimony-service
    apiEndpoints:
      - matrimony
    policies:
      - cors:
          - action:
            optionsSuccessStatus: 204
      - jwt:
          - action:
              secretOrPublicKey: ${JWT_SECRET}
              checkCredentialExistence: false
      - request-transformer:
          # add user id in request header to use in service
          - action:
              headers:
                add:
                  userid: req.user.id
      - proxy:
          - action:
              serviceEndpoint: matrimonysrv
              changeOrigin: true
  - name: matrimony-service-public
    apiEndpoints:
      - matrimonypublic
    policies:
      - proxy:
          - action:
              serviceEndpoint: matrimonysrvpublic
              changeOrigin: true
