http:
  port: ${APP_PORT}
admin:
  port: ${ADMIN_PORT}
  host: ${ADMIN_HOST}
apiEndpoints:
  matrimony:
    host: ${ENDPOINT}
    paths:
      - "/v1/profile/password/change"
      - "/v1/profiles*"
      - "/v1/users/shortlist*"
      - "/v1/users/profile-views*"
      - "/v1/profile/preferences*"
      - "/v1/users/chats*"
      - "/v1/profile/payment/page-viewed"
      # Admin panel URLs
      - "/cp/v1/admins*"
      - "/cp/v1/profiles*"
      - "/cp/v1/employees/earnings*"
      - "/cp/v1/sub-ordinates*"
      - "/cp/v1/payment/page/viewed*"
      # Image URLs
      - "/v1/pellifix/images*"
      - "/v1/profiles/images/uploads"
      # Razorpay
      - "/v1/razor/payment"

  matrimonypublic:
    host: ${ENDPOINT}
    paths:
      - "/v1/health-check"
      - "/v1/reference/drop-down"
      - "/v1/reference/states"
      - "/v1/customer/register"
      - "/v1/customer/login"
      - "/v1/customer/otp/verify"
      - "/v1/customer/otp/generate"
      - "/v1/customer/password/reset"
      - "/v1/customer/password/update*"
        # Admin panel URLs
      - "/cp/v1/admin/auth/login"
      - "/cp/v1/admin/auth/password/reset"
      - "/cp/v1/admin/auth/password/update*"
        # Sub ordinate URLs
      - "/cp/v1/sub-ordinate/auth/login"
      - "/cp/v1/sub-ordinate/auth/password/reset"
      - "/cp/v1/sub-ordinate/auth/password/update*"
        # Associates URLs
      - "/cp/v1/associates/auth/login"
      - "/cp/v1/associates/auth/password/reset"
      - "/cp/v1/associates/auth/password/update*"

serviceEndpoints:
  matrimonysrv:
    url: http://${MATRI_HOST}:${MATRI_SERVICE_PORT}
  matrimonysrvpublic:
    url: http://${MATRI_HOST}:${MATRI_SERVICE_PORT}
policies:
  - basic-auth
  - key-auth
  - cors
  - expression
  - log
  - oauth2
  - proxy
  - rate-limit
  - jwt
  - request-transformer
pipelines:
  - name: matrimony-service
    apiEndpoints:
      - matrimony
    policies:
      - cors:
          - action:
            optionsSuccessStatus: 204
      - jwt:
          - action:
              secretOrPublicKey: ${JWT_SECRET}
              checkCredentialExistence: false
      - request-transformer:
          # add user id in request header to use in service
          - action:
              headers:
                add:
                  userid: req.user.id
      - proxy:
          - action:
              serviceEndpoint: matrimonysrv
              changeOrigin: true
  - name: matrimony-service-public
    apiEndpoints:
      - matrimonypublic
    policies:
      - proxy:
          - action:
              serviceEndpoint: matrimonysrvpublic
              changeOrigin: true
