name: Deploy to ECR

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    name: Build and push to ECR
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: pellifix-backend
          IMAGE_TAG: PROD
        run: |
          docker build --pull -t "$ECR_REGISTRY/$ECR_REPOSITORY/gateway-service" -t "$ECR_REGISTRY/$ECR_REPOSITORY/gateway-service:$IMAGE_TAG" services/gateway-service/ .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY/gateway-service:$IMAGE_TAG
          docker build --pull -t "$ECR_REGISTRY/$ECR_REPOSITORY/api-service" -t "$ECR_REGISTRY/$ECR_REPOSITORY/api-service:$IMAGE_TAG" services/api-service/ .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY/api-service:$IMAGE_TAG
